//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "core_action_reset_frequency")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::core_policy_action::Entity")]
    CorePolicyAction,
}

impl Related<super::core_policy_action::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CorePolicyAction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
